package modelo.entidad;
// Generated May 15, 2020 3:37:35 PM by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Items generated by hbm2java
 */
@Entity
@Table(name="items"
    ,catalog="pizzeriaDSA"
)
public class Items  implements java.io.Serializable {


     private Integer idItem;
     private Tipoitems tipoitems;
     private String nombreItem;
     private String tamano;
     private float precio;
     private String descripcion;

    public Items() {
    }

	
    public Items(Tipoitems tipoitems, String nombreItem, String tamano, float precio) {
        this.tipoitems = tipoitems;
        this.nombreItem = nombreItem;
        this.tamano = tamano;
        this.precio = precio;
    }
    public Items(Tipoitems tipoitems, String nombreItem, String tamano, float precio, String descripcion) {
       this.tipoitems = tipoitems;
       this.nombreItem = nombreItem;
       this.tamano = tamano;
       this.precio = precio;
       this.descripcion = descripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idItem", unique=true, nullable=false)
    public Integer getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(Integer idItem) {
        this.idItem = idItem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTipoItem", nullable=false)
    public Tipoitems getTipoitems() {
        return this.tipoitems;
    }
    
    public void setTipoitems(Tipoitems tipoitems) {
        this.tipoitems = tipoitems;
    }

    
    @Column(name="nombreItem", nullable=false, length=100)
    public String getNombreItem() {
        return this.nombreItem;
    }
    
    public void setNombreItem(String nombreItem) {
        this.nombreItem = nombreItem;
    }

    
    @Column(name="tamano", nullable=false, length=45)
    public String getTamano() {
        return this.tamano;
    }
    
    public void setTamano(String tamano) {
        this.tamano = tamano;
    }

    
    @Column(name="precio", nullable=false, precision=10)
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }

    
    @Column(name="descripcion", length=150)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }





}


