package modelo.entidad;
// Generated May 15, 2020 3:37:35 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipoitems generated by hbm2java
 */
@Entity
@Table(name="tipoitems"
    ,catalog="pizzeriaDSA"
)
public class Tipoitems  implements java.io.Serializable {


     private Integer idTipoItem;
     private String nombreTipoItem;

    public Tipoitems() {
    }

	
    public Tipoitems(String nombreTipoItem) {
        this.nombreTipoItem = nombreTipoItem;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTipoItem", unique=true, nullable=false)
    public Integer getIdTipoItem() {
        return this.idTipoItem;
    }
    
    public void setIdTipoItem(Integer idTipoItem) {
        this.idTipoItem = idTipoItem;
    }

    
    @Column(name="nombreTipoItem", nullable=false, length=50)
    public String getNombreTipoItem() {
        return this.nombreTipoItem;
    }
    
    public void setNombreTipoItem(String nombreTipoItem) {
        this.nombreTipoItem = nombreTipoItem;
    }


}


