package modelo.entidad;
// Generated May 15, 2020 3:37:35 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="pizzeriaDSA"
)
public class Usuarios  implements java.io.Serializable {

     private Integer idUsuario;
     private Tipousuarios tipousuarios;
     private String username;
     private String pwd;
     private String nombreCliente;
     private String apellidoCliente;
     private String documento;

    public Usuarios() {
    }

	
    public Usuarios(Tipousuarios tipousuarios, String nombreCliente, String apellidoCliente, String documento) {
        this.tipousuarios = tipousuarios;
        this.nombreCliente = nombreCliente;
        this.apellidoCliente = apellidoCliente;
        this.documento = documento;
    }
    public Usuarios(Tipousuarios tipousuarios, String username, String pwd, String nombreCliente, String apellidoCliente, String documento) {
       this.tipousuarios = tipousuarios;
       this.username = username;
       this.pwd = pwd;
       this.nombreCliente = nombreCliente;
       this.apellidoCliente = apellidoCliente;
       this.documento = documento;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idUsuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTipoUsuario", nullable=false)
    public Tipousuarios getTipousuarios() {
        return this.tipousuarios;
    }
    
    public void setTipousuarios(Tipousuarios tipousuarios) {
        this.tipousuarios = tipousuarios;
    }

    
    @Column(name="username", length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="pwd", length=100)
    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    
    @Column(name="nombreCliente", nullable=false, length=45)
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }

    
    @Column(name="apellidoCliente", nullable=false, length=45)
    public String getApellidoCliente() {
        return this.apellidoCliente;
    }
    
    public void setApellidoCliente(String apellidoCliente) {
        this.apellidoCliente = apellidoCliente;
    }

    
    @Column(name="documento", nullable=false, length=45)
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }


}


